player1 = int(input("Enter runs score by player 1 in 60 balls: "))
player2 = int(input("Enter runs score by player 2 in 60 balls: "))
player3 = int(input("Enter runs score by player 2 in 60 balls: "))
strike1 = player1 * 100 / 60
strike2 = player2 * 100 / 60
strike3 = player3 * 100 / 60
print("Strike rate of player1: ")
print(strike1)
print("Strike rate of player2: ")
print(strike2)
print("Strike rate of player3: ")
print(strike3)
print("Runs scored by player 1 if he played more 60 balls: ")
print(player1 * 2)
print("Runs scored by player 2 if he played more 60 balls: ")
print(player2 * 2)
print("Runs scored by player 3 if he played more 60 balls: ")
print(player3 * 2)
print("Maximum number of sixes hit by player1: ")
print(player1 // 6)
print("Maximum number of sixes hit by player2: ")
print(player2 // 6)
print("Maximum number of sixes hit by player3: ")
print(player3 // 6)
